### ISSUE TITLE
How to load previous trained model and finetune?

### ISSUE THREAD

**Issue by tiger990111** [SamYuen101234/Masked_Face_Recognition#22]
Hi dear,
I have downloaded the Model1 and tended to finetune it. But it raise error that

Traceback (most recent call last):
  File "main2.py", line 81, in <module>
    facenet, optimizer, scheduler = load(name)
  File "/root/maskedface/Masked_Face_Recognition/train.py", line 26, in load
    model = checkpoint['model']
TypeError: 'FaceNet2' object is not subscriptable

so how to load your trained model1?
And where is the code of finetune?

**Comment by tiger990111** [comment]
> Hi dear, I have downloaded the Model1 and tended to finetune it. But it raise error that
> 
> Traceback (most recent call last): File "main2.py", line 81, in facenet, optimizer, scheduler = load(name) File "/root/maskedface/Masked_Face_Recognition/train.py", line 26, in load model = checkpoint['model'] TypeError: 'FaceNet2' object is not subscriptable
> 
> so how to load your trained model1? And where is the code of finetune?

**Comment by tiger990111** [comment]
yeah I find that it's a model file, so just

facenet = torch.load('./models/' + name) 

to load it. Don't use load(name).
